version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
  
jobs:
  build:
    working_directory: ~/ExampleApplication
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: 
          name: Update npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
      - run: 
          name: Install npm 
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-{{ checksum "package-lock.json" }}

  deploy:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - run: 
          name: Deploy Application
          command: |
            ssh -o StrictHostKeyChecking=no  $ubuntu@ec2-3-248-252-26.eu-west-1.compute.amazonaws.com "rm -rf Devops60-/; git clone https://github.com/newVnetures/Devops60-.git; source Devops60-/deploy.sh"